package html

import (
	"html/template"
	"strings"
)

var templateFuncs = template.FuncMap{
	"fieldShortName": fieldShortName,
}

// fieldShortName strips the group prefix from path for display in the nav
// tree, e.g. ("payments.fee", "payments") -> "fee". A top-level field whose
// path equals its own prefix (no dot) is returned unchanged, since
// TrimPrefix is a no-op when "prefix." isn't actually a prefix of path.
func fieldShortName(path, prefix string) string {
	return strings.TrimPrefix(path, prefix+".")
}

var pageTemplate = template.Must(template.New("page").Funcs(templateFuncs).Parse(pageTemplateSrc))

const pageTemplateSrc = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ .Title }}</title>
<style>
{{ .CSS }}
</style>
</head>
<body>
<div class="decree-doc">
  <header class="decree-header">
    <div>
      <h1>{{ .Title }}</h1>
      {{- if .Sub }}
      <div class="sub">{{ .Sub }}</div>
      {{- end }}
    </div>
  </header>
  {{- if .Validations }}
  <section class="validations">
    <h2 class="group">Validations</h2>
    {{- range .Validations }}
    <div class="validation-item {{ .Severity }}">
      <div class="validation-head">{{ .Label }}</div>
      <pre><code>{{ .Rule }}</code></pre>
      <p class="validation-message">{{ .Message }}</p>
    </div>
    {{- end }}
  </section>
  {{- end }}
  <div class="decree-body">
    <nav class="decree-nav">
      {{- range .Groups }}
      {{- $prefix := .Prefix }}
      <div class="group-title">{{ .Prefix }}</div>
      {{- range .Fields }}
      <a href="#{{ .Path }}"{{ if .Deprecated }} class="deprecated"{{ end }}>{{ fieldShortName .Path $prefix }}</a>
      {{- end }}
      {{- end }}
      <div class="footer">{{ .NumField }} fields · {{ .NumType }} types<br>Generated by decree-docs</div>
    </nav>
    <main class="decree-main">
      {{- range .Groups }}
      <h2 class="group">{{ .Prefix }}</h2>
      {{- range .Fields }}
      {{ template "field" . }}
      {{- end }}
      {{- end }}
    </main>
  </div>
</div>
</body>
</html>
`

func init() {
	template.Must(pageTemplate.New("field").Parse(fieldTemplateSrc))
}

const fieldTemplateSrc = `
<section class="field-card" id="{{ .Path }}">
  <div class="field-head">
    {{- if .Title }}
    <h3>{{ .Title }}</h3>
    <code class="mono">{{ .Path }}</code>
    {{- else }}
    <code class="mono path{{ if .Deprecated }} deprecated{{ end }}">{{ .Path }}</code>
    {{- end }}
    <span class="type-chip mono">{{ .Type }}{{ if .Format }} · {{ .Format }}{{ end }}</span>
  </div>
  {{- if .Badges }}
  <div class="badge-row">
    {{- range .Badges }}
    <span class="badge {{ .Class }}">{{ if .Icon }}{{ .Icon }} {{ end }}{{ .Label }}</span>
    {{- end }}
  </div>
  {{- end }}
  {{- if .Deprecated }}
  <div class="deprecation-notice">
    <span>↪</span>
    {{- if .RedirectTo }}
    <span>Deprecated — use <code>{{ .RedirectTo }}</code> instead.</span>
    {{- else }}
    <span>Deprecated — this field should no longer be used.</span>
    {{- end }}
  </div>
  {{- end }}
  {{- if .Description }}
  <p class="desc">{{ .Description }}</p>
  {{- end }}
  {{- if .Sensitive }}
  <div class="sensitive-mask">
    <span>🔒</span> ● ● ● ● ● ● ● ●
    <span class="note">value masked</span>
  </div>
  {{- else }}
  {{- if or .Default .Tags }}
  <div class="meta-row">
    {{- if .Default }}
    <span>Default <code class="default-chip mono">{{ .Default }}</code></span>
    {{- end }}
    {{- if .Tags }}
    <span>Tags {{ range .Tags }}<span class="tag-chip mono">{{ . }}</span>{{ end }}</span>
    {{- end }}
  </div>
  {{- end }}
  {{- if .Examples }}
  <div class="examples">
    <div class="label">{{ if gt (len .Examples) 1 }}Examples{{ else }}Example{{ end }}</div>
    {{- range .Examples }}
    <div class="example-item">
      {{- if .Name }}
      <div class="name">{{ .Name }}</div>
      {{- end }}
      <code class="value mono">{{ .Value }}</code>
      {{- if .Summary }}
      <div class="summary">{{ .Summary }}</div>
      {{- end }}
    </div>
    {{- end }}
  </div>
  {{- end }}
  {{- end }}
  {{- if .Constraints }}
  <div class="constraints">
    <div class="label">Constraints</div>
    <ul>
      {{- range .Constraints }}
      <li>{{ . }}</li>
      {{- end }}
    </ul>
  </div>
  {{- end }}
  {{- if .ExternalDocs }}
  <div class="external-docs">
    <a href="{{ .ExternalDocs.URL }}">{{ if .ExternalDocs.Description }}{{ .ExternalDocs.Description }}{{ else }}{{ .ExternalDocs.URL }}{{ end }} ↗</a>
  </div>
  {{- end }}
</section>
`
