coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        target: 80%

ignore:
  - "cmd/decree"
  - "api/centralconfig/**"
  - "internal/storage/dbstore/**"
  - "cmd/server/openapi.json"
  - "docs/**"
