.nh
.TH "DECREE" "1" "Jan 2026" "OpenDecree" "OpenDecree CLI"

.SH NAME
decree-server - Server information and management


.SH SYNOPSIS
\fBdecree server [flags]\fP


.SH DESCRIPTION
Query server metadata, version, and enabled features.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for server


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--insecure\fP[=true]
	skip TLS verification

.PP
\fB-o\fP, \fB--output\fP="table"
	output format: table, json, yaml

.PP
\fB--role\fP="superadmin"
	actor role (x-role header)

.PP
\fB--server\fP="localhost:9090"
	gRPC server address

.PP
\fB--subject\fP=""
	actor identity (x-subject header)

.PP
\fB--tenant-id\fP=""
	auth tenant ID (x-tenant-id header)

.PP
\fB--token\fP=""
	JWT bearer token

.PP
\fB--wait\fP[=false]
	wait for the server to be ready before executing the command

.PP
\fB--wait-timeout\fP="60s"
	maximum time to wait for server readiness


.SH SEE ALSO
\fBdecree(1)\fP, \fBdecree-server-info(1)\fP
