name: Project automation

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    uses: opendecree/.github/.github/workflows/add-to-project.yml@main
    secrets: inherit
